Version: Release1.1 #Version.·
Language: en_US.properties #LanguageFile,Support English and chinese,chinese is zh_CN.properties. 
HttpUrl: https://speedy-nodes-nyc.moralis.io/9b440aeffb73e2e2865ff0a6/polygon/mainnet/ #blockchain httpurl
Symbol: MATIC #NaiveToken Symbol.
ChainName: "Polygon Mainnet" #chainname 
ChainID: 137 #blockchain id
OnPlayerLoginRegisterWallet: true #whether to create a wallet when the player logs in, true = yes.
# playerCanInsertTheyOwnSeed: true #Whether to enable players to enter their own wallets, true = yes. WARNING! This feature will happen in the future, don't enable this!
IsMysql: false #whether to use mysql database. 
MysqlUrl: mysql://localhost:3306/SFTFinance #Mysql Url. Mysql 
MysqlUser: root #Mysql user. 
MysqlPassword: 1234 #Mysql password.